### ISSUE TITLE
Y-sorting does not work as intended for other players

### ISSUE THREAD

**Issue by ValeFolken** [LLAMARPG/game#203]
Walking behind a lamp post works properly for myself, but if another player views me doing it, I appear in a layer above the lamp post instead.

This does not seem to be the case for trees though.  Very odd inconsistency.

No error reports.

**Comment by Warren1001** [comment]
fixed in 0.8.3.0. other players weren't y-sorting

**Comment by ValeFolken** [comment]
Still an issue.  If you enter the fringe of the lamp post you will be seen moving behind it, but if you touch the base of the lamp post you will pop out in front of it - on the other person's screen.  I think this can be fixed by stretching the blocked territory a few more pixels north.

**Comment by Warren1001** [comment]
if you can show evidence of areas where this happens, feel free to reopen this
