### ISSUE TITLE
[Bug] Players able to move during dialogue

### ISSUE THREAD

**Issue by ValeFolken** [LLAMARPG/game#205]
Players are able to move during dialogue, but this only occurs on the initial interaction. Once you're able to select talking options you are static again.

No error report.

**Comment by Warren1001** [comment]
i think i fixed this but i could be misremembering, re-open if i'm just dumb. 0.8.1.0

**Comment by ValeFolken** [comment]
This is still an issue.  I don't have permission to reopen, box greyed.

**Comment by Warren1001** [comment]
fixed in 0.8.3.0
