### ISSUE TITLE
Unattained skills able to be added to spellbooks

### ISSUE THREAD

**Issue by ValeFolken** [LLAMARPG/game#271]
### Online or Offline?

Not in-game or N/A

### Explain the bug in detail

At the Spellscribe NPC you can allocate unattained skills to the book and save them.  Unattained skills still don't show up in combat though luckily.  Maybe make them unclickable unless slvl =>1

No error code

### Log File Raw Text

```Text

```

**Comment by Warren1001** [comment]
should be fixed, i didnt test it

**Comment by ValeFolken** [comment]
Not fixed, but also there was nothing to pull on GH desktop so maybe you forgot to push?

**Comment by Warren1001** [comment]
couldve sworn i pushed, but i pushed now

**Comment by Warren1001** [comment]
right now, passives aren't meant to be allocated. this will be changed in the future when spellscribing is implemented the way its suppose to be.

**Comment by ValeFolken** [comment]
Are passives active all the time then, or non-functional?
